<?php

namespace Container1jw78kO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4ZNRFs3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4ZNRFs3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4ZNRFs3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animal' => ['privates', '.errored..service_locator.4ZNRFs3.App\\Entity\\Animal', NULL, 'Cannot autowire service ".service_locator.4ZNRFs3": it references class "App\\Entity\\Animal" but no such service exists.'],
        ], [
            'animal' => 'App\\Entity\\Animal',
        ]);
    }
}
